name: Build and upload Docker images

on:
    pull_request: 
        paths: 
            - '**/Dockerfile'

jobs:
    build_and_publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Find changed Dockerfiles
              run: git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep 'Dockerfile'
