name: Build and upload Docker images

on:
  # pull_request:
  push:
    paths:
      - "**/Dockerfile"
    branches: 
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Get all changed Dockerfiles
        id: changed_dockerfiles
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **/Dockerfile

      - name: List all changed Dockerfiles
        if: steps.changed_dockerfiles.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_DOCKERFILES: ${{ steps.changed_dockerfiles.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_DOCKERFILES}; do
            echo "$file was changed"
          done

      - name: Log in to Docker Hub
        if: steps.changed_dockerfiles.outputs.any_changed == 'true' 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push
        if: steps.changed_dockerfiles.outputs.any_changed == 'true' 
        env:
          ALL_CHANGED_DOCKERFILES: ${{ steps.changed_dockerfiles.outputs.all_changed_files }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          for file in ${ALL_CHANGED_DOCKERFILES}; do
            echo "Building ${file}..."
            current_tag=$(grep '^FROM' ${file} | awk -F[:@] '{print $2}')
            current_date=$(date +"%Y%m%d")
            image_name=$(grep '^LABEL IMAGE_NAME' ${file} | awk -F= '{gsub(/"/, "", $2); print $2}')
            tag=${DOCKER_USERNAME}/${image_name}:${current_tag}-${current_date}
            docker build -f ${file} -t ${tag} .
            docker push ${tag}
            docker tag ${tag} ${DOCKER_USERNAME}/${image_name}:${current_tag}
            docker push ${DOCKER_USERNAME}/${image_name}:${current_tag}
            docker tag ${tag} ${DOCKER_USERNAME}/${image_name}:latest
            docker push ${DOCKER_USERNAME}/${image_name}:latest
          done

